title: QSMS Builds
description: Official build releases, updates, and guides for the QSms app — your solution for reliable SMS campaigns.
show_downloads: true
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
