title: QSMS
description: Official build releases, updates, and guides for the QSms app — your solution for reliable SMS campaigns.
logo: https://partha11.github.io/qsms-builds/assets/img/logo.png
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: true
baseurl: ""
url: https://partha11.github.io/qsms-builds/
repository: Partha11/qsms-builds
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag